# Multiple Linear Regression Algo

In [1]:
import numpy as np
X = np.array([[0.038,0.051,0.062,0.022,-0.044],[-0.002, -0.045, -0.051, -0.026, -0.008],[0.085, 0.051, 0.044, -0.006, -0.046],[-0.089, -0.045, -0.012, -0.037, 0.012],[0.005, -0.045, -0.036, 0.022, 0.004],[-0.093, -0.045, -0.041, -0.019, -0.069],[-0.045, 0.051, -0.047, -0.016, -0.04],[0.064, 0.051, -0.002, 0.067, 0.091]])
print(X)

[[ 0.038  0.051  0.062  0.022 -0.044]
 [-0.002 -0.045 -0.051 -0.026 -0.008]
 [ 0.085  0.051  0.044 -0.006 -0.046]
 [-0.089 -0.045 -0.012 -0.037  0.012]
 [ 0.005 -0.045 -0.036  0.022  0.004]
 [-0.093 -0.045 -0.041 -0.019 -0.069]
 [-0.045  0.051 -0.047 -0.016 -0.04 ]
 [ 0.064  0.051 -0.002  0.067  0.091]]


In [17]:
y = np.array([151,75,141,206,135,97,138,63])
y

array([151,  75, 141, 206, 135,  97, 138,  63])

In [22]:
n_samples, n_features = X.shape

In [276]:
weights = np.zeros(n_features)
bias = 0
lr = 1.6
lamb = 0.5

for i in range(5):
        print(f'weights:{weights}')
        print(f'bias:{bias}')
        y_pred = np.dot(X, weights) + bias 
        dw = (-1 / n_samples) * np.dot(X.T, (y_pred - y))
        db = (-1 / n_samples) * np.sum(y_pred - y)
        weights += lr * dw
        bias += lr * db    

In [269]:
for i in range(5):
        print(f'weights:{weights}')
        print(f'bias:{bias}')
        y_pred = np.dot(X, weights) + bias 
        dw = (-1 / n_samples) * (np.dot(X.T, (y_pred - y)) + 2*lamb*weights)
        db = (-1 / n_samples) * np.sum(y_pred - y)
        weights += lr * dw
        bias += lr * db   

weights:[0. 0. 0. 0. 0.]
bias:0
weights:[-2.257   0.4116 -1.236  -0.7912 -3.4396]
bias:201.20000000000002
weights:[-2.55084527 -0.21573419  1.12404682 -1.69447058 -2.14986098]
bias:80.37312059999998
weights:[-3.68236754 -0.13784763  1.0024518  -2.24856785 -3.53760416]
bias:152.93632112558498
weights:[-4.04020794 -0.4195566   2.11318714 -2.78815175 -3.18881881]
bias:109.36065608522699


# With Lasso L1

In [ ]:
lamb = 1
for i in range(1000):
        print(f'weights:{weights}')
        print(f'bias:{bias}')
        y_pred = np.dot(X, weights) + bias 
        dw = (-1 / n_samples) * (np.dot(X.T, (y_pred - y)) + lamb*np.sum(np.abs(weights)))
        db = (-1 / n_samples) * np.sum(y_pred - y)
        cost = (1/ n_samples)*sum([val**2 for val in (y-y_pred)]) + 2lamb*np.sum(np.abs(weights))
        print(f'error:{cost}')
        weights += lr * dw
        bias += lr * db

# With Ridge L2 and cost function

In [280]:
lamb = 1
for i in range(1000):
        print(f'weights:{weights}')
        print(f'bias:{bias}')
        y_pred = np.dot(X, weights) + bias 
        dw = (-1 / n_samples) * (np.dot(X.T, (y_pred - y)) + 2*lamb*weights)
        db = (-1 / n_samples) * np.sum(y_pred - y)
        cost = (1/ n_samples)*sum([val**2 for val in (y-y_pred)]) + 2*lamb*np.sum(weights)
        print(f'error:{cost}')
        weights += lr * dw
        bias += lr * db 

weights:[-6.39242134 -0.85305004  4.30154995 -4.70772757 -4.45952846]
bias:125.7159979379445
error:1810.5831256554834
weights:[-5.11393707 -0.68244003  3.44123996 -3.76618205 -3.56762277]
bias:125.7159979379445
error:1820.5486904568825
weights:[-4.35648998 -0.58431938  2.92316908 -3.20638612 -3.03915423]
bias:125.72687859780225
error:1826.4579433573338
weights:[-3.90762816 -0.52799046  2.61141751 -2.87355777 -2.72581283]
bias:125.7266700112863
error:1829.9599432340517
weights:[-3.64166746 -0.49565432  2.42373297 -2.6756549  -2.54015933]
bias:125.7304721540473
error:1832.0336710371243
weights:[-3.48404137 -0.47712882  2.31082156 -2.55797954 -2.43008281]
bias:125.73032420671514
error:1833.2616570768837
weights:[-3.39063398 -0.4665163   2.24286215 -2.4880017  -2.36486529]
bias:125.73165294126547
error:1833.9884958334371
weights:[-3.33526804 -0.46045054  2.20198744 -2.44638796 -2.32619762]
bias:125.7315742303559
error:1834.4188038580805
weights:[-3.30245514 -0.45698403  2.17739146 -2.42163

error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.452

weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.3853

error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.452

weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.3853

error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.452

error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.7322225571068
error:1835.0429161513503
weights:[-3.25468375 -0.45240685  2.1402881  -2.38531261 -2.2699511 ]
bias:125.73222255710678
error:1835.0429161513498
weights:[-3.25468375 -0.452